"use client";
import type { Metadata } from "next";
import { Geist_Mono, Lexend } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { useEffect } from "react";
import { useRouter, usePathname, redirect } from "next/navigation";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const currentPath = usePathname();
  useEffect(() => {
    if (currentPath === "/") router.push("/generateOtp");
  }, [currentPath]);

  return (
    <html lang="en">
      <body
        className={`${lexend.variable} ${geistMono.variable} font-lexend antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
