"use client";
import type { Metadata } from "next";
import { Geist_Mono, Lexend } from "next/font/google";
import "@/app/globals.css";
import { ToastContainer } from "react-toastify";
import Header from "@/src/components/Header";
import { usePathname } from "next/navigation";
import Avatar from "@mui/material/Avatar";

import { sideBarData } from "@/src/helpers/staticData";
import SideBar from "@/src/components/Sidebar";
import ActiveHeader from "@/src/components/ActiveHeader";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export function getCookie(name: string) {
  const value = `${document.cookie}`;
  const parts = value.split(`; ${name}=`);
  if (parts.length === 2) return parts.pop().split(";").shift();
  return null;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();

  const isAuthenticated = getCookie("AuthToken") !== null;
  return (
    <html lang="en">
      <body
        className={`${lexend.variable} ${geistMono.variable} font-lexend antialiased p-0 m-0 h-screen `}
      >
        <div className={`${lexend.variable} flex flex-col font-lexend`}>
          {isAuthenticated ? (
            <div className="flex h-screen">
              <SideBar />

              <div className="flex flex-col h-full w-[80%]">
                <div>
                  <ActiveHeader />
                </div>

                {children}
              </div>
            </div>
          ) : (
            <div>
              <Header />
              {children}
            </div>
          )}

          {path !== "/verifyOtp" && !isAuthenticated && (
            <div className="flex justify-center  sm:h-[15vh] items-end w-[175vw] sm:w-full">
              <p className="text-white">Copyright © 2025 Gst.IO</p>
            </div>
          )}
          <ToastContainer />
        </div>
      </body>
    </html>
  );
}
